name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  docs:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
  
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        case: 'npm'
    - name: Build documentation
      run: |
          npm install
          npm run generate-doc
    - name: Publish
      uses: shaynlink/ghpages@v0.3.0
      env:
        GH_PAT: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: docs/
        BRANCH: main
